//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FamilyFood.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class FamilyFoodEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“FamilyFoodEntities”部分中的连接字符串初始化新 FamilyFoodEntities 对象。
        /// </summary>
        public FamilyFoodEntities() : base("name=FamilyFoodEntities", "FamilyFoodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FamilyFoodEntities 对象。
        /// </summary>
        public FamilyFoodEntities(string connectionString) : base(connectionString, "FamilyFoodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 FamilyFoodEntities 对象。
        /// </summary>
        public FamilyFoodEntities(EntityConnection connection) : base(connection, "FamilyFoodEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<card> card
        {
            get
            {
                if ((_card == null))
                {
                    _card = base.CreateObjectSet<card>("card");
                }
                return _card;
            }
        }
        private ObjectSet<card> _card;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<cate> cate
        {
            get
            {
                if ((_cate == null))
                {
                    _cate = base.CreateObjectSet<cate>("cate");
                }
                return _cate;
            }
        }
        private ObjectSet<cate> _cate;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<dapei> dapei
        {
            get
            {
                if ((_dapei == null))
                {
                    _dapei = base.CreateObjectSet<dapei>("dapei");
                }
                return _dapei;
            }
        }
        private ObjectSet<dapei> _dapei;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ucard> ucard
        {
            get
            {
                if ((_ucard == null))
                {
                    _ucard = base.CreateObjectSet<ucard>("ucard");
                }
                return _ucard;
            }
        }
        private ObjectSet<ucard> _ucard;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<user_table> user_table
        {
            get
            {
                if ((_user_table == null))
                {
                    _user_table = base.CreateObjectSet<user_table>("user_table");
                }
                return _user_table;
            }
        }
        private ObjectSet<user_table> _user_table;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<comment> comment
        {
            get
            {
                if ((_comment == null))
                {
                    _comment = base.CreateObjectSet<comment>("comment");
                }
                return _comment;
            }
        }
        private ObjectSet<comment> _comment;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<family> family
        {
            get
            {
                if ((_family == null))
                {
                    _family = base.CreateObjectSet<family>("family");
                }
                return _family;
            }
        }
        private ObjectSet<family> _family;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<food> food
        {
            get
            {
                if ((_food == null))
                {
                    _food = base.CreateObjectSet<food>("food");
                }
                return _food;
            }
        }
        private ObjectSet<food> _food;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 card EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocard(card card)
        {
            base.AddObject("card", card);
        }
    
        /// <summary>
        /// 用于向 cate EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocate(cate cate)
        {
            base.AddObject("cate", cate);
        }
    
        /// <summary>
        /// 用于向 dapei EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTodapei(dapei dapei)
        {
            base.AddObject("dapei", dapei);
        }
    
        /// <summary>
        /// 用于向 ucard EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToucard(ucard ucard)
        {
            base.AddObject("ucard", ucard);
        }
    
        /// <summary>
        /// 用于向 user_table EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTouser_table(user_table user_table)
        {
            base.AddObject("user_table", user_table);
        }
    
        /// <summary>
        /// 用于向 comment EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTocomment(comment comment)
        {
            base.AddObject("comment", comment);
        }
    
        /// <summary>
        /// 用于向 family EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTofamily(family family)
        {
            base.AddObject("family", family);
        }
    
        /// <summary>
        /// 用于向 food EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTofood(food food)
        {
            base.AddObject("food", food);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="card")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class card : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 card 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static card Createcard(global::System.Int32 id)
        {
            card card = new card();
            card.id = id;
            return card;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String message
        {
            get
            {
                return _message;
            }
            set
            {
                OnmessageChanging(value);
                ReportPropertyChanging("message");
                _message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("message");
                OnmessageChanged();
            }
        }
        private global::System.String _message;
        partial void OnmessageChanging(global::System.String value);
        partial void OnmessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String summary
        {
            get
            {
                return _summary;
            }
            set
            {
                OnsummaryChanging(value);
                ReportPropertyChanging("summary");
                _summary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("summary");
                OnsummaryChanged();
            }
        }
        private global::System.String _summary;
        partial void OnsummaryChanging(global::System.String value);
        partial void OnsummaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int32> _fid;
        partial void OnfidChanging(Nullable<global::System.Int32> value);
        partial void OnfidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="cate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cate : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 cate 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static cate Createcate(global::System.Int32 id)
        {
            cate cate = new cate();
            cate.id = id;
            return cate;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String catecontent
        {
            get
            {
                return _catecontent;
            }
            set
            {
                OncatecontentChanging(value);
                ReportPropertyChanging("catecontent");
                _catecontent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("catecontent");
                OncatecontentChanged();
            }
        }
        private global::System.String _catecontent;
        partial void OncatecontentChanging(global::System.String value);
        partial void OncatecontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int32> _fid;
        partial void OnfidChanging(Nullable<global::System.Int32> value);
        partial void OnfidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comment : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 comment 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static comment Createcomment(global::System.Int32 id)
        {
            comment comment = new comment();
            comment.id = id;
            return comment;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comment1
        {
            get
            {
                return _comment1;
            }
            set
            {
                Oncomment1Changing(value);
                ReportPropertyChanging("comment1");
                _comment1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comment1");
                Oncomment1Changed();
            }
        }
        private global::System.String _comment1;
        partial void Oncomment1Changing(global::System.String value);
        partial void Oncomment1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int32> _fid;
        partial void OnfidChanging(Nullable<global::System.Int32> value);
        partial void OnfidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="dapei")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dapei : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 dapei 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static dapei Createdapei(global::System.Int32 id)
        {
            dapei dapei = new dapei();
            dapei.id = id;
            return dapei;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dp
        {
            get
            {
                return _dp;
            }
            set
            {
                OndpChanging(value);
                ReportPropertyChanging("dp");
                _dp = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dp");
                OndpChanged();
            }
        }
        private global::System.String _dp;
        partial void OndpChanging(global::System.String value);
        partial void OndpChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int32> _fid;
        partial void OnfidChanging(Nullable<global::System.Int32> value);
        partial void OnfidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="family")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class family : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 family 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static family Createfamily(global::System.Int32 id)
        {
            family family = new family();
            family.id = id;
            return family;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String signature
        {
            get
            {
                return _signature;
            }
            set
            {
                OnsignatureChanging(value);
                ReportPropertyChanging("signature");
                _signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("signature");
                OnsignatureChanged();
            }
        }
        private global::System.String _signature;
        partial void OnsignatureChanging(global::System.String value);
        partial void OnsignatureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="food")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class food : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 food 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static food Createfood(global::System.Int32 id)
        {
            food food = new food();
            food.id = id;
            return food;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> kg
        {
            get
            {
                return _kg;
            }
            set
            {
                OnkgChanging(value);
                ReportPropertyChanging("kg");
                _kg = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("kg");
                OnkgChanged();
            }
        }
        private Nullable<global::System.Double> _kg;
        partial void OnkgChanging(Nullable<global::System.Double> value);
        partial void OnkgChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dt
        {
            get
            {
                return _dt;
            }
            set
            {
                OndtChanging(value);
                ReportPropertyChanging("dt");
                _dt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dt");
                OndtChanged();
            }
        }
        private Nullable<global::System.DateTime> _dt;
        partial void OndtChanging(Nullable<global::System.DateTime> value);
        partial void OndtChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int32> _fid;
        partial void OnfidChanging(Nullable<global::System.Int32> value);
        partial void OnfidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> caid
        {
            get
            {
                return _caid;
            }
            set
            {
                OncaidChanging(value);
                ReportPropertyChanging("caid");
                _caid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("caid");
                OncaidChanged();
            }
        }
        private Nullable<global::System.Int32> _caid;
        partial void OncaidChanging(Nullable<global::System.Int32> value);
        partial void OncaidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _status;
        partial void OnstatusChanging(Nullable<global::System.Int32> value);
        partial void OnstatusChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="ucard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ucard : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ucard 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static ucard Createucard(global::System.Int32 id)
        {
            ucard ucard = new ucard();
            ucard.id = id;
            return ucard;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String taste
        {
            get
            {
                return _taste;
            }
            set
            {
                OntasteChanging(value);
                ReportPropertyChanging("taste");
                _taste = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("taste");
                OntasteChanged();
            }
        }
        private global::System.String _taste;
        partial void OntasteChanging(global::System.String value);
        partial void OntasteChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fruit
        {
            get
            {
                return _fruit;
            }
            set
            {
                OnfruitChanging(value);
                ReportPropertyChanging("fruit");
                _fruit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fruit");
                OnfruitChanged();
            }
        }
        private global::System.String _fruit;
        partial void OnfruitChanging(global::System.String value);
        partial void OnfruitChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vegetables
        {
            get
            {
                return _vegetables;
            }
            set
            {
                OnvegetablesChanging(value);
                ReportPropertyChanging("vegetables");
                _vegetables = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vegetables");
                OnvegetablesChanged();
            }
        }
        private global::System.String _vegetables;
        partial void OnvegetablesChanging(global::System.String value);
        partial void OnvegetablesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dishes
        {
            get
            {
                return _dishes;
            }
            set
            {
                OndishesChanging(value);
                ReportPropertyChanging("dishes");
                _dishes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dishes");
                OndishesChanged();
            }
        }
        private global::System.String _dishes;
        partial void OndishesChanging(global::System.String value);
        partial void OndishesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uid
        {
            get
            {
                return _uid;
            }
            set
            {
                OnuidChanging(value);
                ReportPropertyChanging("uid");
                _uid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uid");
                OnuidChanged();
            }
        }
        private Nullable<global::System.Int32> _uid;
        partial void OnuidChanging(Nullable<global::System.Int32> value);
        partial void OnuidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="family_foodModel", Name="user_table")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_table : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 user_table 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static user_table Createuser_table(global::System.Int32 id)
        {
            user_table user_table = new user_table();
            user_table.id = id;
            return user_table;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nick
        {
            get
            {
                return _nick;
            }
            set
            {
                OnnickChanging(value);
                ReportPropertyChanging("nick");
                _nick = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nick");
                OnnickChanged();
            }
        }
        private global::System.String _nick;
        partial void OnnickChanging(global::System.String value);
        partial void OnnickChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pass
        {
            get
            {
                return _pass;
            }
            set
            {
                OnpassChanging(value);
                ReportPropertyChanging("pass");
                _pass = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pass");
                OnpassChanged();
            }
        }
        private global::System.String _pass;
        partial void OnpassChanging(global::System.String value);
        partial void OnpassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private Nullable<global::System.Int32> _sex;
        partial void OnsexChanging(Nullable<global::System.Int32> value);
        partial void OnsexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String heath
        {
            get
            {
                return _heath;
            }
            set
            {
                OnheathChanging(value);
                ReportPropertyChanging("heath");
                _heath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("heath");
                OnheathChanged();
            }
        }
        private global::System.String _heath;
        partial void OnheathChanging(global::System.String value);
        partial void OnheathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> fid
        {
            get
            {
                return _fid;
            }
            set
            {
                OnfidChanging(value);
                ReportPropertyChanging("fid");
                _fid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fid");
                OnfidChanged();
            }
        }
        private Nullable<global::System.Int32> _fid;
        partial void OnfidChanging(Nullable<global::System.Int32> value);
        partial void OnfidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _status;
        partial void OnstatusChanging(Nullable<global::System.Int32> value);
        partial void OnstatusChanged();

        #endregion

    
    }

    #endregion

    
}
